# Generated by Django 2.2.12 on 2020-04-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200423_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reports',
            field=models.IntegerField(default=0),
        ),
    ]
