# Generated by Django 2.2.12 on 2020-04-26 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_post_reports'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='reports',
            new_name='downvotes',
        ),
    ]
