# Generated by Django 2.2.12 on 2020-04-26 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200426_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ytlink',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
