# Generated by Django 2.2.12 on 2020-04-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200426_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ytlink',
            field=models.TextField(null=True),
        ),
    ]
