# Generated by Django 2.2.12 on 2020-04-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200428_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='contact',
            field=models.TextField(max_length=30),
        ),
    ]
