# Generated by Django 2.2.12 on 2020-04-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200428_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.BooleanField(choices=[('Commercial', 'Commercial'), ('Voluntary', 'Voluntary')]),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='contact',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
