# Generated by Django 2.2.12 on 2020-04-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200428_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Voluntary', 'Voluntary')], max_length=200),
        ),
    ]
