# Generated by Django 2.2.12 on 2020-04-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200428_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
