# Generated by Django 2.2.12 on 2020-04-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200428_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('Comercial', 'Comercial'), ('Voluntariado', 'Voluntariado')], max_length=200),
        ),
    ]
