# Generated by Django 2.2.12 on 2020-05-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_post_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
