# Generated by Django 2.2.12 on 2020-05-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_post_ncomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='yt_link',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
