# Generated by Django 2.2.12 on 2020-05-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20200506_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='contact',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.TextField(max_length=30),
        ),
    ]
